# https://docs.readthedocs.io/en/latest/yaml-config.html
version: 2
build:
  image: latest
python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - trinity
        - doc
