name: Build AppImage
on: [push]

jobs:
  build:
    name: AppImage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: echo $GITHUB_WORKSPACE
      - run: ls $GITHUB_WORKSPACE
