name: Build AppImage
on: [push]

jobs:
  build:
    name: AppImage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: cd $GITHUB_WORKSPACE/appimage
      - run: ROOT=$(dirname $(pwd))
      - run: PIP_REQUIREMENTS="$ROOT" ./linuxdeploy-x86_64.AppImage --plugin python --appdir AppDir -i triceratops.png -d trinity.desktop --custom-apprun=AppRun
      - run: ./appimagetool-x86_64.AppImage AppDir Trinity-x86_64.AppImage
      - uses: actions/upload-artifact@master
        with: Trinity-x86_64.AppImage
        path: Trinity-x86_64.AppImage
