name: Build AppImage
on: [push]

jobs:
  build:
    name: AppImage
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libsnappy-dev libsqlite3-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          cd $GITHUB_WORKSPACE/appimage

          # First, we need ipget
          wget https://dist.ipfs.io/ipget/v0.5.0/ipget_v0.5.0_linux-amd64.tar.gz
          tar -xvf ipget_v0.5.0_linux-amd64.tar.gz

          # Next, we need the appimage binaries
          ./ipget/ipget QmPALFn9oeEwpzYkyUMC7zUEZFFVEE9ug6uSREet7WY9Uc -o bin

          # Build the AppDir
          ROOT=$(dirname $(pwd))
          PIP_REQUIREMENTS="$ROOT" ./bin/linuxdeploy-x86_64.AppImage --plugin python --appdir AppDir -i triceratops.png -d trinity.desktop --custom-apprun=AppRun.trinity

          # Build the first appimage
          ./bin/appimagetool-x86_64.AppImage AppDir Trinity-x86_64.AppImage
          mkdir $GITHUB_WORKSPACE/trinity-appimage
          mv Trinity-x86_64.AppImage $GITHUB_WORKSPACE/trinity-appimage

          # Copy over trinity-beacon's launcher, and build the second appimage
          cp AppRun.trinity-beacon AppDir/AppRun
          ./bin/appimagetool-x86_64.AppImage AppDir Trinity-Beacon-x86_64.AppImage
          mkdir $GITHUB_WORKSPACE/beacon-appimage
          mv Trinity-Beacon-x86_64.AppImage $GITHUB_WORKSPACE/beacon-appimage
      - uses: actions/upload-artifact@master
        with: 
          name: Trinity-x86_64.AppImage
          path: trinity-appimage
      - uses: actions/upload-artifact@master
        with: 
          name: Trinity-Beacon-x86_64.AppImage
          path: beacon-appimage
