name: Build AppImage
on: [push]

jobs:
  build:
    name: AppImage
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libsnappy-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          cd $GITHUB_WORKSPACE/appimage
          ROOT=$(dirname $(pwd))
          PIP_REQUIREMENTS="$ROOT" ./linuxdeploy-x86_64.AppImage --plugin python --appdir AppDir -i triceratops.png -d trinity.desktop --custom-apprun=AppRun.trinity
          ./appimagetool-x86_64.AppImage AppDir Trinity-x86_64.AppImage
          mkdir $GITHUB_WORKSPACE/trinity-appimage
          mv Trinity-x86_64.AppImage $GITHUB_WORKSPACE/trinity-appimage

          cp AppRun.trinity-beacon AppDir/AppRun
          ./appimagetool-x86_64.AppImage AppDir Trinity-Beacon-x86_64.AppImage
          mkdir $GITHUB_WORKSPACE/beacon-appimage
          mv Trinity-Beacon-x86_64.AppImage $GITHUB_WORKSPACE/beacon-appimage
      - uses: actions/upload-artifact@master
        with: 
          name: Trinity-x86_64.AppImage
          path: trinity-appimage
      - uses: actions/upload-artifact@master
        with: 
          name: Trinity-Beacon-x86_64.AppImage
          path: beacon-appimage
